### ISSUE TITLE
为什么在Fragment中使用这个控件会报错呢？

### ISSUE THREAD

**Issue by philadelphia** [baiiu/DropDownMenu#30]
如果将该控件写在一个Fragment中使用，就会报下面的错误。谢谢
FATAL EXCEPTION: main
                                                                        Process: com.baiiu.dropdownmenu, PID: 15011
                                                                        java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewParent android.view.View.getParent()' on a null object reference
                                                                            at android.view.ViewGroup.addViewInner(ViewGroup.java:3879)
                                                                            at android.view.ViewGroup.addView(ViewGroup.java:3733)
                                                                            at android.view.ViewGroup.addView(ViewGroup.java:3709)
                                                                            at com.baiiu.filter.DropDownMenu.setContentView(DropDownMenu.java:76)
                                                                            at com.baiiu.filter.DropDownMenu.onFinishInflate(DropDownMenu.java:57)

**Comment by baiiu** [comment]
噢噢，这个我抽时间查下哈，您也可以看下源码，然后反馈给我~

**Comment by JamesMarts** [comment]
这个问题怎么解决的啊 我也是这个问题

**Comment by baiiu** [comment]
@philadelphia @JamesMarts 我上传了fragment示例，并没有出现这个问题，你看看你们的id设置了么

**Comment by philadelphia** [comment]
是因为DropDownMenu.java Line57里面 setContentView(findViewById(R.id.mFilterContentView));我们没有用到。但是导入的时候没有删除。所以导致空指针异常 @JamesMarts

**Comment by philadelphia** [comment]
再请教作者一个问题了。如果我在一个Fragment中使用该控件。然后该fragment在Mainactivity中。MainActivity有三个Fragment。在最下面使用RadioGroup来切换。那请问怎么让下拉矿的灰色至于RadioGroup之上呢，他们不是一个视图层。谢谢！

**Comment by NicodeLee** [comment]
fragment 使用这里的代码一样报错 ` setContentView(findViewById(R.id.mFilterContentView));`
`Caused by: java.lang.IllegalArgumentException: Cannot add a null child view to a ViewGroup`
如果把ContentView换为Textview没问题，使用RecyclerView就报错

补充：内容view id必须命名为 `mFilterContentView`不报错了。这个应该说明下。

@philadelphia 
@baiiu
